// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageCatalog creates a new instance of MockMessageCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageCatalog {
	mock := &MockMessageCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageCatalog is an autogenerated mock type for the MessageCatalog type
type MockMessageCatalog struct {
	mock.Mock
}

type MockMessageCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageCatalog) EXPECT() *MockMessageCatalog_Expecter {
	return &MockMessageCatalog_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockMessageCatalog
func (_mock *MockMessageCatalog) Get(message messages.MessageKey) string {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(messages.MessageKey) string); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessageCatalog_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMessageCatalog_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - message messages.MessageKey
func (_e *MockMessageCatalog_Expecter) Get(message interface{}) *MockMessageCatalog_Get_Call {
	return &MockMessageCatalog_Get_Call{Call: _e.mock.On("Get", message)}
}

func (_c *MockMessageCatalog_Get_Call) Run(run func(message messages.MessageKey)) *MockMessageCatalog_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messages.MessageKey
		if args[0] != nil {
			arg0 = args[0].(messages.MessageKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageCatalog_Get_Call) Return(s string) *MockMessageCatalog_Get_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessageCatalog_Get_Call) RunAndReturn(run func(message messages.MessageKey) string) *MockMessageCatalog_Get_Call {
	_c.Call.Return(run)
	return _c
}
