// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// newMockparameterWithDescriptionFromMessageCatalog creates a new instance of mockparameterWithDescriptionFromMessageCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockparameterWithDescriptionFromMessageCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockparameterWithDescriptionFromMessageCatalog {
	mock := &mockparameterWithDescriptionFromMessageCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockparameterWithDescriptionFromMessageCatalog is an autogenerated mock type for the parameterWithDescriptionFromMessageCatalog type
type mockparameterWithDescriptionFromMessageCatalog struct {
	mock.Mock
}

type mockparameterWithDescriptionFromMessageCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *mockparameterWithDescriptionFromMessageCatalog) EXPECT() *mockparameterWithDescriptionFromMessageCatalog_Expecter {
	return &mockparameterWithDescriptionFromMessageCatalog_Expecter{mock: &_m.Mock}
}

// GetDefaultValue provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetDefaultValue() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultValue")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultValue'
type mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call struct {
	*mock.Call
}

// GetDefaultValue is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetDefaultValue() *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call{Call: _e.mock.On("GetDefaultValue")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call) Return(v any) *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call) RunAndReturn(run func() any) *mockparameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescription provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetDescription() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetDescription() *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call{Call: _e.mock.On("GetDescription")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call) Return(s string) *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call) RunAndReturn(run func() string) *mockparameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvVarName provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetEnvVarName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvVarName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvVarName'
type mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call struct {
	*mock.Call
}

// GetEnvVarName is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetEnvVarName() *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call{Call: _e.mock.On("GetEnvVarName")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call) Return(s string) *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call) RunAndReturn(run func() string) *mockparameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlagName provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetFlagName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFlagName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlagName'
type mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call struct {
	*mock.Call
}

// GetFlagName is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetFlagName() *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call{Call: _e.mock.On("GetFlagName")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call) Return(s string) *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call) RunAndReturn(run func() string) *mockparameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	_c.Call.Return(run)
	return _c
}

// GetHiddenFlag provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetHiddenFlag() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHiddenFlag")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHiddenFlag'
type mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call struct {
	*mock.Call
}

// GetHiddenFlag is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetHiddenFlag() *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call{Call: _e.mock.On("GetHiddenFlag")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call) Return(b bool) *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call) RunAndReturn(run func() bool) *mockparameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type mockparameterWithDescriptionFromMessageCatalog_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetID() *mockparameterWithDescriptionFromMessageCatalog_GetID_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetID_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetID_Call) Return(s string) *mockparameterWithDescriptionFromMessageCatalog_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetID_Call) RunAndReturn(run func() string) *mockparameterWithDescriptionFromMessageCatalog_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordToLog provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) GetRecordToLog() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRecordToLog")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordToLog'
type mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call struct {
	*mock.Call
}

// GetRecordToLog is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) GetRecordToLog() *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call{Call: _e.mock.On("GetRecordToLog")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call) Return(b bool) *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call) RunAndReturn(run func() bool) *mockparameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	_c.Call.Return(run)
	return _c
}

// getDescriptionKey provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) getDescriptionKey() messages.MessageKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getDescriptionKey")
	}

	var r0 messages.MessageKey
	if returnFunc, ok := ret.Get(0).(func() messages.MessageKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.MessageKey)
		}
	}
	return r0
}

// mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDescriptionKey'
type mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call struct {
	*mock.Call
}

// getDescriptionKey is a helper method to define mock.On call
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) getDescriptionKey() *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call{Call: _e.mock.On("getDescriptionKey")}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call) Run(run func()) *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call) Return(messageKey messages.MessageKey) *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call {
	_c.Call.Return(messageKey)
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call) RunAndReturn(run func() messages.MessageKey) *mockparameterWithDescriptionFromMessageCatalog_getDescriptionKey_Call {
	_c.Call.Return(run)
	return _c
}

// setDescription provides a mock function for the type mockparameterWithDescriptionFromMessageCatalog
func (_mock *mockparameterWithDescriptionFromMessageCatalog) setDescription(description string) {
	_mock.Called(description)
	return
}

// mockparameterWithDescriptionFromMessageCatalog_setDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setDescription'
type mockparameterWithDescriptionFromMessageCatalog_setDescription_Call struct {
	*mock.Call
}

// setDescription is a helper method to define mock.On call
//   - description string
func (_e *mockparameterWithDescriptionFromMessageCatalog_Expecter) setDescription(description interface{}) *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call {
	return &mockparameterWithDescriptionFromMessageCatalog_setDescription_Call{Call: _e.mock.On("setDescription", description)}
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call) Run(run func(description string)) *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call) Return() *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call) RunAndReturn(run func(description string)) *mockparameterWithDescriptionFromMessageCatalog_setDescription_Call {
	_c.Run(run)
	return _c
}
