// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/inputs/defaultparameters"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/inputs/parser"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/lifecyclesignaler"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/modeselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/orchestrator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/filesystem/files"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/matlabrootselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/matlabstartingdirselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/http/client"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/http/server"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/logger"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession"
	directory2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory/matlabfiles"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processdetails"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processlauncher"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabroot"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabversion"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionstore"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources/codingguidelines"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources/plaintextlivecodegeneration"
	server3 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server/configurator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server/sdk"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools"
	evalmatlabcode2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/evalmatlabcode"
	listavailablematlabs2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/listavailablematlabs"
	startmatlabsession2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/startmatlabsession"
	stopmatlabsession2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/stopmatlabsession"
	checkmatlabcode2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/checkmatlabcode"
	detectmatlabtoolboxes2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/detectmatlabtoolboxes"
	evalmatlabcode3 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/evalmatlabcode"
	runmatlabfile2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/runmatlabfile"
	runmatlabtestfile2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/messagecatalog"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/os"
	watchdog2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/watchdog/process"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/filefacade"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/iofacade"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/checkmatlabcode"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/detectmatlabtoolboxes"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/evalmatlabcode"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/listavailablematlabs"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/runmatlabfile"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/startmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/stopmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/utils/pathvalidator"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/processhandler"
	client2 "github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/client"
	server2 "github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/server"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/server/handler"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/socket"
)

// Injectors from wire.go:

func Initialize(serverDefinition ApplicationDefinition) *Application {
	osFacade := osfacade.New()
	messageCatalog := messagecatalog.New()
	factory := defaultparameters.NewFactory(messageCatalog)
	parserParser := parser.New(osFacade, factory, serverDefinition)
	configFactory := config.NewFactory(parserParser, osFacade)
	filesFactory := files.NewFactory(osFacade)
	directoryFactory := directory.NewFactory(configFactory, filesFactory, osFacade)
	loggerFactory := logger.NewFactory(configFactory, directoryFactory, filesFactory, osFacade)
	processManager := os.New(osFacade)
	processHandler := processhandler.New(loggerFactory, processManager)
	handlerFactory := handler.NewFactory(loggerFactory, processHandler)
	serverFactory := server.NewFactory(osFacade)
	factory2 := server2.NewFactory(serverFactory, loggerFactory, handlerFactory)
	socketFactory := socket.NewFactory(directoryFactory, osFacade)
	watchdogWatchdog := watchdog.New(loggerFactory, osFacade, processHandler, processManager, handlerFactory, factory2, socketFactory)
	lifecycleSignaler := lifecyclesignaler.New()
	sdkFactory := sdk.NewFactory(configFactory, serverDefinition)
	fileFacade := filefacade.New()
	getter := matlabroot.New(osFacade, fileFacade)
	ioFacade := iofacade.New()
	matlabversionGetter := matlabversion.New(osFacade, ioFacade)
	matlabLocator := matlablocator.New(getter, matlabversionGetter)
	matlabFiles := matlabfiles.New()
	factory3 := directory2.NewFactory(osFacade, directoryFactory, matlabFiles)
	processDetails := processdetails.New(osFacade)
	matlabProcessLauncher := processlauncher.New()
	processFactory := process.New(osFacade, loggerFactory, directoryFactory, configFactory)
	clientFactory := client.NewFactory()
	factory4 := client2.NewFactory(osFacade, loggerFactory, clientFactory)
	watchdog3 := watchdog2.New(processFactory, factory4, loggerFactory, socketFactory)
	starter := localmatlabsession.NewStarter(factory3, processDetails, matlabProcessLauncher, watchdog3)
	matlabServices := matlabservices.New(matlabLocator, starter)
	store := matlabsessionstore.New(loggerFactory, lifecycleSignaler)
	matlabsessionclientFactory := matlabsessionclient.NewFactory(clientFactory)
	matlabManager := matlabmanager.New(matlabServices, store, matlabsessionclientFactory)
	usecase := listavailablematlabs.New(matlabManager)
	tool := listavailablematlabs2.New(loggerFactory, usecase)
	startmatlabsessionUsecase := startmatlabsession.New(matlabManager)
	startmatlabsessionTool := startmatlabsession2.New(loggerFactory, configFactory, startmatlabsessionUsecase)
	stopmatlabsessionUsecase := stopmatlabsession.New(matlabManager)
	stopmatlabsessionTool := stopmatlabsession2.New(loggerFactory, stopmatlabsessionUsecase)
	pathValidator := pathvalidator.New(osFacade)
	evalmatlabcodeUsecase := evalmatlabcode.New(pathValidator)
	evalmatlabcodeTool := evalmatlabcode2.New(loggerFactory, configFactory, evalmatlabcodeUsecase, matlabManager)
	matlabRootSelector := matlabrootselector.New(configFactory, matlabManager)
	matlabStartingDirSelector := matlabstartingdirselector.New(configFactory, osFacade)
	globalMATLAB := globalmatlab.New(matlabManager, matlabRootSelector, matlabStartingDirSelector, configFactory)
	tool2 := evalmatlabcode3.New(loggerFactory, configFactory, evalmatlabcodeUsecase, globalMATLAB)
	checkmatlabcodeUsecase := checkmatlabcode.New(pathValidator)
	checkmatlabcodeTool := checkmatlabcode2.New(loggerFactory, checkmatlabcodeUsecase, globalMATLAB)
	detectmatlabtoolboxesUsecase := detectmatlabtoolboxes.New()
	detectmatlabtoolboxesTool := detectmatlabtoolboxes2.New(loggerFactory, detectmatlabtoolboxesUsecase, globalMATLAB)
	runmatlabfileUsecase := runmatlabfile.New(pathValidator)
	runmatlabfileTool := runmatlabfile2.New(loggerFactory, configFactory, runmatlabfileUsecase, globalMATLAB)
	runmatlabtestfileUsecase := runmatlabtestfile.New(pathValidator)
	runmatlabtestfileTool := runmatlabtestfile2.New(loggerFactory, runmatlabtestfileUsecase, globalMATLAB)
	resource := codingguidelines.New(loggerFactory)
	plaintextlivecodegenerationResource := plaintextlivecodegeneration.New(loggerFactory)
	configuratorConfigurator := configurator.New(configFactory, tool, startmatlabsessionTool, stopmatlabsessionTool, evalmatlabcodeTool, tool2, checkmatlabcodeTool, detectmatlabtoolboxesTool, runmatlabfileTool, runmatlabtestfileTool, resource, plaintextlivecodegenerationResource)
	serverServer := server3.New(sdkFactory, loggerFactory, lifecycleSignaler, configuratorConfigurator)
	orchestratorOrchestrator := orchestrator.New(messageCatalog, lifecycleSignaler, serverDefinition, configFactory, serverServer, watchdog3, loggerFactory, processManager, globalMATLAB, directoryFactory)
	modeSelector := modeselector.New(configFactory, parserParser, watchdogWatchdog, orchestratorOrchestrator, osFacade)
	application := &Application{
		ModeSelector:      modeSelector,
		MessageCatalog:    messageCatalog,
		HTTPClientFactory: clientFactory,
		HTTPServerFactory: serverFactory,
		LoggerFactory:     loggerFactory,
	}
	return application
}

// wire.go:

type Application struct {
	ModeSelector      *modeselector.ModeSelector
	MessageCatalog    *messagecatalog.MessageCatalog
	HTTPClientFactory *client.Factory
	HTTPServerFactory *server.Factory
	LoggerFactory     *logger.Factory
}

type ApplicationDefinition interface {
	Name() string
	Title() string
	Instructions() string
	Parameters() []entities.Parameter
	Dependencies(resources definition.DependenciesProviderResources) (any, error)
	Tools(resources definition.ToolsProviderResources) []tools.Tool
}
