// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBuildInfo creates a new instance of MockBuildInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuildInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuildInfo {
	mock := &MockBuildInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBuildInfo is an autogenerated mock type for the BuildInfo type
type MockBuildInfo struct {
	mock.Mock
}

type MockBuildInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuildInfo) EXPECT() *MockBuildInfo_Expecter {
	return &MockBuildInfo_Expecter{mock: &_m.Mock}
}

// FullVersion provides a mock function for the type MockBuildInfo
func (_mock *MockBuildInfo) FullVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FullVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBuildInfo_FullVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullVersion'
type MockBuildInfo_FullVersion_Call struct {
	*mock.Call
}

// FullVersion is a helper method to define mock.On call
func (_e *MockBuildInfo_Expecter) FullVersion() *MockBuildInfo_FullVersion_Call {
	return &MockBuildInfo_FullVersion_Call{Call: _e.mock.On("FullVersion")}
}

func (_c *MockBuildInfo_FullVersion_Call) Run(run func()) *MockBuildInfo_FullVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuildInfo_FullVersion_Call) Return(s string) *MockBuildInfo_FullVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBuildInfo_FullVersion_Call) RunAndReturn(run func() string) *MockBuildInfo_FullVersion_Call {
	_c.Call.Return(run)
	return _c
}
