// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// BaseDir provides a mock function for the type MockConfig
func (_mock *MockConfig) BaseDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_BaseDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseDir'
type MockConfig_BaseDir_Call struct {
	*mock.Call
}

// BaseDir is a helper method to define mock.On call
func (_e *MockConfig_Expecter) BaseDir() *MockConfig_BaseDir_Call {
	return &MockConfig_BaseDir_Call{Call: _e.mock.On("BaseDir")}
}

func (_c *MockConfig_BaseDir_Call) Run(run func()) *MockConfig_BaseDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_BaseDir_Call) Return(s string) *MockConfig_BaseDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_BaseDir_Call) RunAndReturn(run func() string) *MockConfig_BaseDir_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockConfig
func (_mock *MockConfig) Get(key string) (any, messages.Error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) (any, messages.Error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockConfig_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfig_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) Get(key interface{}) *MockConfig_Get_Call {
	return &MockConfig_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockConfig_Get_Call) Run(run func(key string)) *MockConfig_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_Get_Call) Return(v any, error messages.Error) *MockConfig_Get_Call {
	_c.Call.Return(v, error)
	return _c
}

func (_c *MockConfig_Get_Call) RunAndReturn(run func(key string) (any, messages.Error)) *MockConfig_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HelpMode provides a mock function for the type MockConfig
func (_mock *MockConfig) HelpMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HelpMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_HelpMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HelpMode'
type MockConfig_HelpMode_Call struct {
	*mock.Call
}

// HelpMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) HelpMode() *MockConfig_HelpMode_Call {
	return &MockConfig_HelpMode_Call{Call: _e.mock.On("HelpMode")}
}

func (_c *MockConfig_HelpMode_Call) Run(run func()) *MockConfig_HelpMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_HelpMode_Call) Return(b bool) *MockConfig_HelpMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_HelpMode_Call) RunAndReturn(run func() bool) *MockConfig_HelpMode_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeMATLABOnStartup provides a mock function for the type MockConfig
func (_mock *MockConfig) InitializeMATLABOnStartup() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeMATLABOnStartup")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_InitializeMATLABOnStartup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeMATLABOnStartup'
type MockConfig_InitializeMATLABOnStartup_Call struct {
	*mock.Call
}

// InitializeMATLABOnStartup is a helper method to define mock.On call
func (_e *MockConfig_Expecter) InitializeMATLABOnStartup() *MockConfig_InitializeMATLABOnStartup_Call {
	return &MockConfig_InitializeMATLABOnStartup_Call{Call: _e.mock.On("InitializeMATLABOnStartup")}
}

func (_c *MockConfig_InitializeMATLABOnStartup_Call) Run(run func()) *MockConfig_InitializeMATLABOnStartup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_InitializeMATLABOnStartup_Call) Return(b bool) *MockConfig_InitializeMATLABOnStartup_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_InitializeMATLABOnStartup_Call) RunAndReturn(run func() bool) *MockConfig_InitializeMATLABOnStartup_Call {
	_c.Call.Return(run)
	return _c
}

// LogLevel provides a mock function for the type MockConfig
func (_mock *MockConfig) LogLevel() entities.LogLevel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogLevel")
	}

	var r0 entities.LogLevel
	if returnFunc, ok := ret.Get(0).(func() entities.LogLevel); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.LogLevel)
	}
	return r0
}

// MockConfig_LogLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogLevel'
type MockConfig_LogLevel_Call struct {
	*mock.Call
}

// LogLevel is a helper method to define mock.On call
func (_e *MockConfig_Expecter) LogLevel() *MockConfig_LogLevel_Call {
	return &MockConfig_LogLevel_Call{Call: _e.mock.On("LogLevel")}
}

func (_c *MockConfig_LogLevel_Call) Run(run func()) *MockConfig_LogLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_LogLevel_Call) Return(logLevel entities.LogLevel) *MockConfig_LogLevel_Call {
	_c.Call.Return(logLevel)
	return _c
}

func (_c *MockConfig_LogLevel_Call) RunAndReturn(run func() entities.LogLevel) *MockConfig_LogLevel_Call {
	_c.Call.Return(run)
	return _c
}

// PreferredLocalMATLABRoot provides a mock function for the type MockConfig
func (_mock *MockConfig) PreferredLocalMATLABRoot() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreferredLocalMATLABRoot")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_PreferredLocalMATLABRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreferredLocalMATLABRoot'
type MockConfig_PreferredLocalMATLABRoot_Call struct {
	*mock.Call
}

// PreferredLocalMATLABRoot is a helper method to define mock.On call
func (_e *MockConfig_Expecter) PreferredLocalMATLABRoot() *MockConfig_PreferredLocalMATLABRoot_Call {
	return &MockConfig_PreferredLocalMATLABRoot_Call{Call: _e.mock.On("PreferredLocalMATLABRoot")}
}

func (_c *MockConfig_PreferredLocalMATLABRoot_Call) Run(run func()) *MockConfig_PreferredLocalMATLABRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_PreferredLocalMATLABRoot_Call) Return(s string) *MockConfig_PreferredLocalMATLABRoot_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_PreferredLocalMATLABRoot_Call) RunAndReturn(run func() string) *MockConfig_PreferredLocalMATLABRoot_Call {
	_c.Call.Return(run)
	return _c
}

// PreferredMATLABStartingDirectory provides a mock function for the type MockConfig
func (_mock *MockConfig) PreferredMATLABStartingDirectory() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreferredMATLABStartingDirectory")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_PreferredMATLABStartingDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreferredMATLABStartingDirectory'
type MockConfig_PreferredMATLABStartingDirectory_Call struct {
	*mock.Call
}

// PreferredMATLABStartingDirectory is a helper method to define mock.On call
func (_e *MockConfig_Expecter) PreferredMATLABStartingDirectory() *MockConfig_PreferredMATLABStartingDirectory_Call {
	return &MockConfig_PreferredMATLABStartingDirectory_Call{Call: _e.mock.On("PreferredMATLABStartingDirectory")}
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) Run(run func()) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) Return(s string) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) RunAndReturn(run func() string) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// RecordToLogger provides a mock function for the type MockConfig
func (_mock *MockConfig) RecordToLogger(logger entities.Logger) {
	_mock.Called(logger)
	return
}

// MockConfig_RecordToLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordToLogger'
type MockConfig_RecordToLogger_Call struct {
	*mock.Call
}

// RecordToLogger is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockConfig_Expecter) RecordToLogger(logger interface{}) *MockConfig_RecordToLogger_Call {
	return &MockConfig_RecordToLogger_Call{Call: _e.mock.On("RecordToLogger", logger)}
}

func (_c *MockConfig_RecordToLogger_Call) Run(run func(logger entities.Logger)) *MockConfig_RecordToLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_RecordToLogger_Call) Return() *MockConfig_RecordToLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfig_RecordToLogger_Call) RunAndReturn(run func(logger entities.Logger)) *MockConfig_RecordToLogger_Call {
	_c.Run(run)
	return _c
}

// ServerInstanceID provides a mock function for the type MockConfig
func (_mock *MockConfig) ServerInstanceID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerInstanceID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_ServerInstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerInstanceID'
type MockConfig_ServerInstanceID_Call struct {
	*mock.Call
}

// ServerInstanceID is a helper method to define mock.On call
func (_e *MockConfig_Expecter) ServerInstanceID() *MockConfig_ServerInstanceID_Call {
	return &MockConfig_ServerInstanceID_Call{Call: _e.mock.On("ServerInstanceID")}
}

func (_c *MockConfig_ServerInstanceID_Call) Run(run func()) *MockConfig_ServerInstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_ServerInstanceID_Call) Return(s string) *MockConfig_ServerInstanceID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_ServerInstanceID_Call) RunAndReturn(run func() string) *MockConfig_ServerInstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldShowMATLABDesktop provides a mock function for the type MockConfig
func (_mock *MockConfig) ShouldShowMATLABDesktop() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShouldShowMATLABDesktop")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_ShouldShowMATLABDesktop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldShowMATLABDesktop'
type MockConfig_ShouldShowMATLABDesktop_Call struct {
	*mock.Call
}

// ShouldShowMATLABDesktop is a helper method to define mock.On call
func (_e *MockConfig_Expecter) ShouldShowMATLABDesktop() *MockConfig_ShouldShowMATLABDesktop_Call {
	return &MockConfig_ShouldShowMATLABDesktop_Call{Call: _e.mock.On("ShouldShowMATLABDesktop")}
}

func (_c *MockConfig_ShouldShowMATLABDesktop_Call) Run(run func()) *MockConfig_ShouldShowMATLABDesktop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_ShouldShowMATLABDesktop_Call) Return(b bool) *MockConfig_ShouldShowMATLABDesktop_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_ShouldShowMATLABDesktop_Call) RunAndReturn(run func() bool) *MockConfig_ShouldShowMATLABDesktop_Call {
	_c.Call.Return(run)
	return _c
}

// UseSingleMATLABSession provides a mock function for the type MockConfig
func (_mock *MockConfig) UseSingleMATLABSession() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseSingleMATLABSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_UseSingleMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseSingleMATLABSession'
type MockConfig_UseSingleMATLABSession_Call struct {
	*mock.Call
}

// UseSingleMATLABSession is a helper method to define mock.On call
func (_e *MockConfig_Expecter) UseSingleMATLABSession() *MockConfig_UseSingleMATLABSession_Call {
	return &MockConfig_UseSingleMATLABSession_Call{Call: _e.mock.On("UseSingleMATLABSession")}
}

func (_c *MockConfig_UseSingleMATLABSession_Call) Run(run func()) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_UseSingleMATLABSession_Call) Return(b bool) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_UseSingleMATLABSession_Call) RunAndReturn(run func() bool) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockConfig
func (_mock *MockConfig) Version() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockConfig_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockConfig_Expecter) Version() *MockConfig_Version_Call {
	return &MockConfig_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockConfig_Version_Call) Run(run func()) *MockConfig_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_Version_Call) Return(s string) *MockConfig_Version_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_Version_Call) RunAndReturn(run func() string) *MockConfig_Version_Call {
	_c.Call.Return(run)
	return _c
}

// VersionMode provides a mock function for the type MockConfig
func (_mock *MockConfig) VersionMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VersionMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_VersionMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionMode'
type MockConfig_VersionMode_Call struct {
	*mock.Call
}

// VersionMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) VersionMode() *MockConfig_VersionMode_Call {
	return &MockConfig_VersionMode_Call{Call: _e.mock.On("VersionMode")}
}

func (_c *MockConfig_VersionMode_Call) Run(run func()) *MockConfig_VersionMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_VersionMode_Call) Return(b bool) *MockConfig_VersionMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_VersionMode_Call) RunAndReturn(run func() bool) *MockConfig_VersionMode_Call {
	_c.Call.Return(run)
	return _c
}

// WatchdogMode provides a mock function for the type MockConfig
func (_mock *MockConfig) WatchdogMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchdogMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_WatchdogMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchdogMode'
type MockConfig_WatchdogMode_Call struct {
	*mock.Call
}

// WatchdogMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) WatchdogMode() *MockConfig_WatchdogMode_Call {
	return &MockConfig_WatchdogMode_Call{Call: _e.mock.On("WatchdogMode")}
}

func (_c *MockConfig_WatchdogMode_Call) Run(run func()) *MockConfig_WatchdogMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_WatchdogMode_Call) Return(b bool) *MockConfig_WatchdogMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_WatchdogMode_Call) RunAndReturn(run func() bool) *MockConfig_WatchdogMode_Call {
	_c.Call.Return(run)
	return _c
}
