// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenericConfig creates a new instance of MockGenericConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenericConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenericConfig {
	mock := &MockGenericConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenericConfig is an autogenerated mock type for the GenericConfig type
type MockGenericConfig struct {
	mock.Mock
}

type MockGenericConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenericConfig) EXPECT() *MockGenericConfig_Expecter {
	return &MockGenericConfig_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGenericConfig
func (_mock *MockGenericConfig) Get(key string) (any, messages.Error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) (any, messages.Error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockGenericConfig_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGenericConfig_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockGenericConfig_Expecter) Get(key interface{}) *MockGenericConfig_Get_Call {
	return &MockGenericConfig_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockGenericConfig_Get_Call) Run(run func(key string)) *MockGenericConfig_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenericConfig_Get_Call) Return(v any, error messages.Error) *MockGenericConfig_Get_Call {
	_c.Call.Return(v, error)
	return _c
}

func (_c *MockGenericConfig_Get_Call) RunAndReturn(run func(key string) (any, messages.Error)) *MockGenericConfig_Get_Call {
	_c.Call.Return(run)
	return _c
}
