// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Args provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Args() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Args")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockOSLayer_Args_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Args'
type MockOSLayer_Args_Call struct {
	*mock.Call
}

// Args is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Args() *MockOSLayer_Args_Call {
	return &MockOSLayer_Args_Call{Call: _e.mock.On("Args")}
}

func (_c *MockOSLayer_Args_Call) Run(run func()) *MockOSLayer_Args_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Args_Call) Return(strings []string) *MockOSLayer_Args_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockOSLayer_Args_Call) RunAndReturn(run func() []string) *MockOSLayer_Args_Call {
	_c.Call.Return(run)
	return _c
}
