// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse(args []string) ([]entities.Parameter, map[string]any, messages.Error) {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []entities.Parameter
	var r1 map[string]any
	var r2 messages.Error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]entities.Parameter, map[string]any, messages.Error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []entities.Parameter); ok {
		r0 = returnFunc(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Parameter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) map[string]any); ok {
		r1 = returnFunc(args)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func([]string) messages.Error); ok {
		r2 = returnFunc(args)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(messages.Error)
		}
	}
	return r0, r1, r2
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - args []string
func (_e *MockParser_Expecter) Parse(args interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", args)}
}

func (_c *MockParser_Parse_Call) Run(run func(args []string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(parameters []entities.Parameter, stringToV map[string]any, error messages.Error) *MockParser_Parse_Call {
	_c.Call.Return(parameters, stringToV, error)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(args []string) ([]entities.Parameter, map[string]any, messages.Error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
