// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageCatalog creates a new instance of MockMessageCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageCatalog {
	mock := &MockMessageCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageCatalog is an autogenerated mock type for the MessageCatalog type
type MockMessageCatalog struct {
	mock.Mock
}

type MockMessageCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageCatalog) EXPECT() *MockMessageCatalog_Expecter {
	return &MockMessageCatalog_Expecter{mock: &_m.Mock}
}

// GetFromError provides a mock function for the type MockMessageCatalog
func (_mock *MockMessageCatalog) GetFromError(err messages.Error) string {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for GetFromError")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(messages.Error) string); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessageCatalog_GetFromError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromError'
type MockMessageCatalog_GetFromError_Call struct {
	*mock.Call
}

// GetFromError is a helper method to define mock.On call
//   - err messages.Error
func (_e *MockMessageCatalog_Expecter) GetFromError(err interface{}) *MockMessageCatalog_GetFromError_Call {
	return &MockMessageCatalog_GetFromError_Call{Call: _e.mock.On("GetFromError", err)}
}

func (_c *MockMessageCatalog_GetFromError_Call) Run(run func(err messages.Error)) *MockMessageCatalog_GetFromError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messages.Error
		if args[0] != nil {
			arg0 = args[0].(messages.Error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageCatalog_GetFromError_Call) Return(s string) *MockMessageCatalog_GetFromError_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessageCatalog_GetFromError_Call) RunAndReturn(run func(err messages.Error) string) *MockMessageCatalog_GetFromError_Call {
	_c.Call.Return(run)
	return _c
}
