// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockParameter creates a new instance of MockParameter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParameter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParameter {
	mock := &MockParameter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParameter is an autogenerated mock type for the Parameter type
type MockParameter struct {
	mock.Mock
}

type MockParameter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParameter) EXPECT() *MockParameter_Expecter {
	return &MockParameter_Expecter{mock: &_m.Mock}
}

// GetDefaultValue provides a mock function for the type MockParameter
func (_mock *MockParameter) GetDefaultValue() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultValue")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockParameter_GetDefaultValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultValue'
type MockParameter_GetDefaultValue_Call struct {
	*mock.Call
}

// GetDefaultValue is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetDefaultValue() *MockParameter_GetDefaultValue_Call {
	return &MockParameter_GetDefaultValue_Call{Call: _e.mock.On("GetDefaultValue")}
}

func (_c *MockParameter_GetDefaultValue_Call) Run(run func()) *MockParameter_GetDefaultValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetDefaultValue_Call) Return(v any) *MockParameter_GetDefaultValue_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockParameter_GetDefaultValue_Call) RunAndReturn(run func() any) *MockParameter_GetDefaultValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescription provides a mock function for the type MockParameter
func (_mock *MockParameter) GetDescription() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameter_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type MockParameter_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetDescription() *MockParameter_GetDescription_Call {
	return &MockParameter_GetDescription_Call{Call: _e.mock.On("GetDescription")}
}

func (_c *MockParameter_GetDescription_Call) Run(run func()) *MockParameter_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetDescription_Call) Return(s string) *MockParameter_GetDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameter_GetDescription_Call) RunAndReturn(run func() string) *MockParameter_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvVarName provides a mock function for the type MockParameter
func (_mock *MockParameter) GetEnvVarName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvVarName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameter_GetEnvVarName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvVarName'
type MockParameter_GetEnvVarName_Call struct {
	*mock.Call
}

// GetEnvVarName is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetEnvVarName() *MockParameter_GetEnvVarName_Call {
	return &MockParameter_GetEnvVarName_Call{Call: _e.mock.On("GetEnvVarName")}
}

func (_c *MockParameter_GetEnvVarName_Call) Run(run func()) *MockParameter_GetEnvVarName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetEnvVarName_Call) Return(s string) *MockParameter_GetEnvVarName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameter_GetEnvVarName_Call) RunAndReturn(run func() string) *MockParameter_GetEnvVarName_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlagName provides a mock function for the type MockParameter
func (_mock *MockParameter) GetFlagName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFlagName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameter_GetFlagName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlagName'
type MockParameter_GetFlagName_Call struct {
	*mock.Call
}

// GetFlagName is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetFlagName() *MockParameter_GetFlagName_Call {
	return &MockParameter_GetFlagName_Call{Call: _e.mock.On("GetFlagName")}
}

func (_c *MockParameter_GetFlagName_Call) Run(run func()) *MockParameter_GetFlagName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetFlagName_Call) Return(s string) *MockParameter_GetFlagName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameter_GetFlagName_Call) RunAndReturn(run func() string) *MockParameter_GetFlagName_Call {
	_c.Call.Return(run)
	return _c
}

// GetHiddenFlag provides a mock function for the type MockParameter
func (_mock *MockParameter) GetHiddenFlag() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHiddenFlag")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameter_GetHiddenFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHiddenFlag'
type MockParameter_GetHiddenFlag_Call struct {
	*mock.Call
}

// GetHiddenFlag is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetHiddenFlag() *MockParameter_GetHiddenFlag_Call {
	return &MockParameter_GetHiddenFlag_Call{Call: _e.mock.On("GetHiddenFlag")}
}

func (_c *MockParameter_GetHiddenFlag_Call) Run(run func()) *MockParameter_GetHiddenFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetHiddenFlag_Call) Return(b bool) *MockParameter_GetHiddenFlag_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameter_GetHiddenFlag_Call) RunAndReturn(run func() bool) *MockParameter_GetHiddenFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockParameter
func (_mock *MockParameter) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameter_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockParameter_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetID() *MockParameter_GetID_Call {
	return &MockParameter_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockParameter_GetID_Call) Run(run func()) *MockParameter_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetID_Call) Return(s string) *MockParameter_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameter_GetID_Call) RunAndReturn(run func() string) *MockParameter_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordToLog provides a mock function for the type MockParameter
func (_mock *MockParameter) GetRecordToLog() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRecordToLog")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameter_GetRecordToLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordToLog'
type MockParameter_GetRecordToLog_Call struct {
	*mock.Call
}

// GetRecordToLog is a helper method to define mock.On call
func (_e *MockParameter_Expecter) GetRecordToLog() *MockParameter_GetRecordToLog_Call {
	return &MockParameter_GetRecordToLog_Call{Call: _e.mock.On("GetRecordToLog")}
}

func (_c *MockParameter_GetRecordToLog_Call) Run(run func()) *MockParameter_GetRecordToLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameter_GetRecordToLog_Call) Return(b bool) *MockParameter_GetRecordToLog_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameter_GetRecordToLog_Call) RunAndReturn(run func() bool) *MockParameter_GetRecordToLog_Call {
	_c.Call.Return(run)
	return _c
}
