// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type Error interface {
	marker()
	Error() string
}

// StartupErrors_BadFlag_Error defines an error corresponding to the "StartupErrors_BadFlag" message catalog message
type StartupErrors_BadFlag_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_BadFlag_Error satisfy the error interface.
func (e *StartupErrors_BadFlag_Error) Error() string {
	return "StartupErrors_BadFlag_Error"
}

func (*StartupErrors_BadFlag_Error) marker() {}

// New_StartupErrors_BadFlag_Error makes a new StartupErrors_BadFlag_Error error.
func New_StartupErrors_BadFlag_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_BadFlag_Error {
	return &StartupErrors_BadFlag_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_BadSyntax_Error defines an error corresponding to the "StartupErrors_BadSyntax" message catalog message
type StartupErrors_BadSyntax_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_BadSyntax_Error satisfy the error interface.
func (e *StartupErrors_BadSyntax_Error) Error() string {
	return "StartupErrors_BadSyntax_Error"
}

func (*StartupErrors_BadSyntax_Error) marker() {}

// New_StartupErrors_BadSyntax_Error makes a new StartupErrors_BadSyntax_Error error.
func New_StartupErrors_BadSyntax_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_BadSyntax_Error {
	return &StartupErrors_BadSyntax_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_BadValue_Error defines an error corresponding to the "StartupErrors_BadValue" message catalog message
type StartupErrors_BadValue_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_BadValue_Error satisfy the error interface.
func (e *StartupErrors_BadValue_Error) Error() string {
	return "StartupErrors_BadValue_Error"
}

func (*StartupErrors_BadValue_Error) marker() {}

// New_StartupErrors_BadValue_Error makes a new StartupErrors_BadValue_Error error.
func New_StartupErrors_BadValue_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_BadValue_Error {
	return &StartupErrors_BadValue_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_BadValueForEnvVar_Error defines an error corresponding to the "StartupErrors_BadValueForEnvVar" message catalog message
type StartupErrors_BadValueForEnvVar_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_BadValueForEnvVar_Error satisfy the error interface.
func (e *StartupErrors_BadValueForEnvVar_Error) Error() string {
	return "StartupErrors_BadValueForEnvVar_Error"
}

func (*StartupErrors_BadValueForEnvVar_Error) marker() {}

// New_StartupErrors_BadValueForEnvVar_Error makes a new StartupErrors_BadValueForEnvVar_Error error.
func New_StartupErrors_BadValueForEnvVar_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_BadValueForEnvVar_Error {
	return &StartupErrors_BadValueForEnvVar_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_DuplicateParameter_Error defines an error corresponding to the "StartupErrors_DuplicateParameter" message catalog message
type StartupErrors_DuplicateParameter_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_DuplicateParameter_Error satisfy the error interface.
func (e *StartupErrors_DuplicateParameter_Error) Error() string {
	return "StartupErrors_DuplicateParameter_Error"
}

func (*StartupErrors_DuplicateParameter_Error) marker() {}

// New_StartupErrors_DuplicateParameter_Error makes a new StartupErrors_DuplicateParameter_Error error.
func New_StartupErrors_DuplicateParameter_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_DuplicateParameter_Error {
	return &StartupErrors_DuplicateParameter_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_FailedToCreateDirectory_Error defines an error corresponding to the "StartupErrors_FailedToCreateDirectory" message catalog message
type StartupErrors_FailedToCreateDirectory_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateDirectory_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateDirectory_Error) Error() string {
	return "StartupErrors_FailedToCreateDirectory_Error"
}

func (*StartupErrors_FailedToCreateDirectory_Error) marker() {}

// New_StartupErrors_FailedToCreateDirectory_Error makes a new StartupErrors_FailedToCreateDirectory_Error error.
func New_StartupErrors_FailedToCreateDirectory_Error(
	attr0 string,
) *StartupErrors_FailedToCreateDirectory_Error {
	return &StartupErrors_FailedToCreateDirectory_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToCreateFile_Error defines an error corresponding to the "StartupErrors_FailedToCreateFile" message catalog message
type StartupErrors_FailedToCreateFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateFile_Error) Error() string {
	return "StartupErrors_FailedToCreateFile_Error"
}

func (*StartupErrors_FailedToCreateFile_Error) marker() {}

// New_StartupErrors_FailedToCreateFile_Error makes a new StartupErrors_FailedToCreateFile_Error error.
func New_StartupErrors_FailedToCreateFile_Error(
	attr0 string,
) *StartupErrors_FailedToCreateFile_Error {
	return &StartupErrors_FailedToCreateFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToCreateLogFile_Error defines an error corresponding to the "StartupErrors_FailedToCreateLogFile" message catalog message
type StartupErrors_FailedToCreateLogFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateLogFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateLogFile_Error) Error() string {
	return "StartupErrors_FailedToCreateLogFile_Error"
}

func (*StartupErrors_FailedToCreateLogFile_Error) marker() {}

// New_StartupErrors_FailedToCreateLogFile_Error makes a new StartupErrors_FailedToCreateLogFile_Error error.
func New_StartupErrors_FailedToCreateLogFile_Error(
	attr0 string,
) *StartupErrors_FailedToCreateLogFile_Error {
	return &StartupErrors_FailedToCreateLogFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToCreateSubdirectory_Error defines an error corresponding to the "StartupErrors_FailedToCreateSubdirectory" message catalog message
type StartupErrors_FailedToCreateSubdirectory_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateSubdirectory_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateSubdirectory_Error) Error() string {
	return "StartupErrors_FailedToCreateSubdirectory_Error"
}

func (*StartupErrors_FailedToCreateSubdirectory_Error) marker() {}

// New_StartupErrors_FailedToCreateSubdirectory_Error makes a new StartupErrors_FailedToCreateSubdirectory_Error error.
func New_StartupErrors_FailedToCreateSubdirectory_Error(
	attr0 string,
) *StartupErrors_FailedToCreateSubdirectory_Error {
	return &StartupErrors_FailedToCreateSubdirectory_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToGetExecutablePath_Error defines an error corresponding to the "StartupErrors_FailedToGetExecutablePath" message catalog message
type StartupErrors_FailedToGetExecutablePath_Error struct {
}

// Error makes StartupErrors_FailedToGetExecutablePath_Error satisfy the error interface.
func (e *StartupErrors_FailedToGetExecutablePath_Error) Error() string {
	return "StartupErrors_FailedToGetExecutablePath_Error"
}

func (*StartupErrors_FailedToGetExecutablePath_Error) marker() {}

// New_StartupErrors_FailedToGetExecutablePath_Error makes a new StartupErrors_FailedToGetExecutablePath_Error error.
func New_StartupErrors_FailedToGetExecutablePath_Error() *StartupErrors_FailedToGetExecutablePath_Error {
	return &StartupErrors_FailedToGetExecutablePath_Error{}
}

// StartupErrors_FailedToStartWatchdogProcess_Error defines an error corresponding to the "StartupErrors_FailedToStartWatchdogProcess" message catalog message
type StartupErrors_FailedToStartWatchdogProcess_Error struct {
}

// Error makes StartupErrors_FailedToStartWatchdogProcess_Error satisfy the error interface.
func (e *StartupErrors_FailedToStartWatchdogProcess_Error) Error() string {
	return "StartupErrors_FailedToStartWatchdogProcess_Error"
}

func (*StartupErrors_FailedToStartWatchdogProcess_Error) marker() {}

// New_StartupErrors_FailedToStartWatchdogProcess_Error makes a new StartupErrors_FailedToStartWatchdogProcess_Error error.
func New_StartupErrors_FailedToStartWatchdogProcess_Error() *StartupErrors_FailedToStartWatchdogProcess_Error {
	return &StartupErrors_FailedToStartWatchdogProcess_Error{}
}

// StartupErrors_InvalidDisplayMode_Error defines an error corresponding to the "StartupErrors_InvalidDisplayMode" message catalog message
type StartupErrors_InvalidDisplayMode_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidDisplayMode_Error satisfy the error interface.
func (e *StartupErrors_InvalidDisplayMode_Error) Error() string {
	return "StartupErrors_InvalidDisplayMode_Error"
}

func (*StartupErrors_InvalidDisplayMode_Error) marker() {}

// New_StartupErrors_InvalidDisplayMode_Error makes a new StartupErrors_InvalidDisplayMode_Error error.
func New_StartupErrors_InvalidDisplayMode_Error(
	attr0 string,
) *StartupErrors_InvalidDisplayMode_Error {
	return &StartupErrors_InvalidDisplayMode_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidLogLevel_Error defines an error corresponding to the "StartupErrors_InvalidLogLevel" message catalog message
type StartupErrors_InvalidLogLevel_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidLogLevel_Error satisfy the error interface.
func (e *StartupErrors_InvalidLogLevel_Error) Error() string {
	return "StartupErrors_InvalidLogLevel_Error"
}

func (*StartupErrors_InvalidLogLevel_Error) marker() {}

// New_StartupErrors_InvalidLogLevel_Error makes a new StartupErrors_InvalidLogLevel_Error error.
func New_StartupErrors_InvalidLogLevel_Error(
	attr0 string,
) *StartupErrors_InvalidLogLevel_Error {
	return &StartupErrors_InvalidLogLevel_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidParameterKey_Error defines an error corresponding to the "StartupErrors_InvalidParameterKey" message catalog message
type StartupErrors_InvalidParameterKey_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidParameterKey_Error satisfy the error interface.
func (e *StartupErrors_InvalidParameterKey_Error) Error() string {
	return "StartupErrors_InvalidParameterKey_Error"
}

func (*StartupErrors_InvalidParameterKey_Error) marker() {}

// New_StartupErrors_InvalidParameterKey_Error makes a new StartupErrors_InvalidParameterKey_Error error.
func New_StartupErrors_InvalidParameterKey_Error(
	attr0 string,
) *StartupErrors_InvalidParameterKey_Error {
	return &StartupErrors_InvalidParameterKey_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidParameterType_Error defines an error corresponding to the "StartupErrors_InvalidParameterType" message catalog message
type StartupErrors_InvalidParameterType_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_InvalidParameterType_Error satisfy the error interface.
func (e *StartupErrors_InvalidParameterType_Error) Error() string {
	return "StartupErrors_InvalidParameterType_Error"
}

func (*StartupErrors_InvalidParameterType_Error) marker() {}

// New_StartupErrors_InvalidParameterType_Error makes a new StartupErrors_InvalidParameterType_Error error.
func New_StartupErrors_InvalidParameterType_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_InvalidParameterType_Error {
	return &StartupErrors_InvalidParameterType_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_MissingValue_Error defines an error corresponding to the "StartupErrors_MissingValue" message catalog message
type StartupErrors_MissingValue_Error struct {
	Attr0 string
}

// Error makes StartupErrors_MissingValue_Error satisfy the error interface.
func (e *StartupErrors_MissingValue_Error) Error() string {
	return "StartupErrors_MissingValue_Error"
}

func (*StartupErrors_MissingValue_Error) marker() {}

// New_StartupErrors_MissingValue_Error makes a new StartupErrors_MissingValue_Error error.
func New_StartupErrors_MissingValue_Error(
	attr0 string,
) *StartupErrors_MissingValue_Error {
	return &StartupErrors_MissingValue_Error{
		Attr0: attr0,
	}
}

// StartupErrors_ParseFailed_Error defines an error corresponding to the "StartupErrors_ParseFailed" message catalog message
type StartupErrors_ParseFailed_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_ParseFailed_Error satisfy the error interface.
func (e *StartupErrors_ParseFailed_Error) Error() string {
	return "StartupErrors_ParseFailed_Error"
}

func (*StartupErrors_ParseFailed_Error) marker() {}

// New_StartupErrors_ParseFailed_Error makes a new StartupErrors_ParseFailed_Error error.
func New_StartupErrors_ParseFailed_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_ParseFailed_Error {
	return &StartupErrors_ParseFailed_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}
