// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

import "fmt"

type LocaleSpecificCatalog interface {
	Get(MessageKey) string
}

// FromError retrieves the message corresponding to the passed error from the message catalog.
// The holes in the message are filled from the error attributes.
func FromError(catalog LocaleSpecificCatalog, err Error) string {
	switch e := err.(type) {
	case *StartupErrors_BadFlag_Error:
		msg := catalog.Get(StartupErrors_BadFlag)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
			e.Attr2,
		)
	case *StartupErrors_BadSyntax_Error:
		msg := catalog.Get(StartupErrors_BadSyntax)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
			e.Attr2,
		)
	case *StartupErrors_BadValue_Error:
		msg := catalog.Get(StartupErrors_BadValue)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
		)
	case *StartupErrors_BadValueForEnvVar_Error:
		msg := catalog.Get(StartupErrors_BadValueForEnvVar)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
		)
	case *StartupErrors_DuplicateParameter_Error:
		msg := catalog.Get(StartupErrors_DuplicateParameter)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
			e.Attr2,
		)
	case *StartupErrors_FailedToCreateDirectory_Error:
		msg := catalog.Get(StartupErrors_FailedToCreateDirectory)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_FailedToCreateFile_Error:
		msg := catalog.Get(StartupErrors_FailedToCreateFile)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_FailedToCreateLogFile_Error:
		msg := catalog.Get(StartupErrors_FailedToCreateLogFile)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_FailedToCreateSubdirectory_Error:
		msg := catalog.Get(StartupErrors_FailedToCreateSubdirectory)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_FailedToGetExecutablePath_Error:
		msg := catalog.Get(StartupErrors_FailedToGetExecutablePath)
		return msg
	case *StartupErrors_FailedToStartWatchdogProcess_Error:
		msg := catalog.Get(StartupErrors_FailedToStartWatchdogProcess)
		return msg
	case *StartupErrors_InvalidDisplayMode_Error:
		msg := catalog.Get(StartupErrors_InvalidDisplayMode)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_InvalidLogLevel_Error:
		msg := catalog.Get(StartupErrors_InvalidLogLevel)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_InvalidParameterKey_Error:
		msg := catalog.Get(StartupErrors_InvalidParameterKey)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_InvalidParameterType_Error:
		msg := catalog.Get(StartupErrors_InvalidParameterType)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
		)
	case *StartupErrors_MissingValue_Error:
		msg := catalog.Get(StartupErrors_MissingValue)
		return fmt.Sprintf(
			msg,
			e.Attr0,
		)
	case *StartupErrors_ParseFailed_Error:
		msg := catalog.Get(StartupErrors_ParseFailed)
		return fmt.Sprintf(
			msg,
			e.Attr0,
			e.Attr1,
		)
	}

	// Consistency checks of the code generation mean this should never be reached
	return ""
}

func FromErrorMultiLocale(err Error, locale LocaleKey) string {
	catalog := NewCatalog(locale)
	return FromError(catalog, err)
}

func FromGeneralError(catalog LocaleSpecificCatalog, err error) (string, bool) {
	messageError, ok := err.(Error)
	if !ok {
		return "", false
	}
	return FromError(catalog, messageError), true
}

func FromGeneralErrorMultiLocale(err error, locale LocaleKey) (string, bool) {
	messageError, ok := err.(Error)
	if !ok {
		return "", false
	}
	return FromErrorMultiLocale(messageError, locale), true
}
