// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type messageKey string

const (
	CLIMessages_BaseDirDescription                          messageKey = "CLIMessages_BaseDirDescription"
	CLIMessages_DisableTelemetryDescription                 messageKey = "CLIMessages_DisableTelemetryDescription"
	CLIMessages_DisplayModeDescription                      messageKey = "CLIMessages_DisplayModeDescription"
	CLIMessages_HelpDescription                             messageKey = "CLIMessages_HelpDescription"
	CLIMessages_InitializeMATLABOnStartupDescription        messageKey = "CLIMessages_InitializeMATLABOnStartupDescription"
	CLIMessages_InternalUseDescription                      messageKey = "CLIMessages_InternalUseDescription"
	CLIMessages_LogLevelDescription                         messageKey = "CLIMessages_LogLevelDescription"
	CLIMessages_PreferredLocalMATLABRootDescription         messageKey = "CLIMessages_PreferredLocalMATLABRootDescription"
	CLIMessages_PreferredMATLABStartingDirectoryDescription messageKey = "CLIMessages_PreferredMATLABStartingDirectoryDescription"
	CLIMessages_UseSingleMATLABSessionDescription           messageKey = "CLIMessages_UseSingleMATLABSessionDescription"
	CLIMessages_VersionDescription                          messageKey = "CLIMessages_VersionDescription"
	StartupErrors_BadFlag                                   messageKey = "StartupErrors_BadFlag"
	StartupErrors_BadSyntax                                 messageKey = "StartupErrors_BadSyntax"
	StartupErrors_BadValue                                  messageKey = "StartupErrors_BadValue"
	StartupErrors_BadValueForEnvVar                         messageKey = "StartupErrors_BadValueForEnvVar"
	StartupErrors_DuplicateParameter                        messageKey = "StartupErrors_DuplicateParameter"
	StartupErrors_FailedToCreateDirectory                   messageKey = "StartupErrors_FailedToCreateDirectory"
	StartupErrors_FailedToCreateFile                        messageKey = "StartupErrors_FailedToCreateFile"
	StartupErrors_FailedToCreateLogFile                     messageKey = "StartupErrors_FailedToCreateLogFile"
	StartupErrors_FailedToCreateSubdirectory                messageKey = "StartupErrors_FailedToCreateSubdirectory"
	StartupErrors_FailedToGetExecutablePath                 messageKey = "StartupErrors_FailedToGetExecutablePath"
	StartupErrors_FailedToStartWatchdogProcess              messageKey = "StartupErrors_FailedToStartWatchdogProcess"
	StartupErrors_GenericInitializeFailure                  messageKey = "StartupErrors_GenericInitializeFailure"
	StartupErrors_InvalidDisplayMode                        messageKey = "StartupErrors_InvalidDisplayMode"
	StartupErrors_InvalidLogLevel                           messageKey = "StartupErrors_InvalidLogLevel"
	StartupErrors_InvalidParameterKey                       messageKey = "StartupErrors_InvalidParameterKey"
	StartupErrors_InvalidParameterType                      messageKey = "StartupErrors_InvalidParameterType"
	StartupErrors_MissingValue                              messageKey = "StartupErrors_MissingValue"
	StartupErrors_ParseFailed                               messageKey = "StartupErrors_ParseFailed"
)

// MessageKey is a specific type to signify message catalog keys.
type MessageKey interface {
	unseal() messageKey
}

func (m messageKey) unseal() messageKey { return m }
