// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDefaultParameterFactory creates a new instance of MockDefaultParameterFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDefaultParameterFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDefaultParameterFactory {
	mock := &MockDefaultParameterFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDefaultParameterFactory is an autogenerated mock type for the DefaultParameterFactory type
type MockDefaultParameterFactory struct {
	mock.Mock
}

type MockDefaultParameterFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDefaultParameterFactory) EXPECT() *MockDefaultParameterFactory_Expecter {
	return &MockDefaultParameterFactory_Expecter{mock: &_m.Mock}
}

// DefaultParameters provides a mock function for the type MockDefaultParameterFactory
func (_mock *MockDefaultParameterFactory) DefaultParameters() []entities.Parameter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultParameters")
	}

	var r0 []entities.Parameter
	if returnFunc, ok := ret.Get(0).(func() []entities.Parameter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Parameter)
		}
	}
	return r0
}

// MockDefaultParameterFactory_DefaultParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultParameters'
type MockDefaultParameterFactory_DefaultParameters_Call struct {
	*mock.Call
}

// DefaultParameters is a helper method to define mock.On call
func (_e *MockDefaultParameterFactory_Expecter) DefaultParameters() *MockDefaultParameterFactory_DefaultParameters_Call {
	return &MockDefaultParameterFactory_DefaultParameters_Call{Call: _e.mock.On("DefaultParameters")}
}

func (_c *MockDefaultParameterFactory_DefaultParameters_Call) Run(run func()) *MockDefaultParameterFactory_DefaultParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefaultParameterFactory_DefaultParameters_Call) Return(parameters []entities.Parameter) *MockDefaultParameterFactory_DefaultParameters_Call {
	_c.Call.Return(parameters)
	return _c
}

func (_c *MockDefaultParameterFactory_DefaultParameters_Call) RunAndReturn(run func() []entities.Parameter) *MockDefaultParameterFactory_DefaultParameters_Call {
	_c.Call.Return(run)
	return _c
}
