// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// LookupEnv provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) LookupEnv(key string) (string, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LookupEnv")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockOSLayer_LookupEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupEnv'
type MockOSLayer_LookupEnv_Call struct {
	*mock.Call
}

// LookupEnv is a helper method to define mock.On call
//   - key string
func (_e *MockOSLayer_Expecter) LookupEnv(key interface{}) *MockOSLayer_LookupEnv_Call {
	return &MockOSLayer_LookupEnv_Call{Call: _e.mock.On("LookupEnv", key)}
}

func (_c *MockOSLayer_LookupEnv_Call) Run(run func(key string)) *MockOSLayer_LookupEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_LookupEnv_Call) Return(s string, b bool) *MockOSLayer_LookupEnv_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockOSLayer_LookupEnv_Call) RunAndReturn(run func(key string) (string, bool)) *MockOSLayer_LookupEnv_Call {
	_c.Call.Return(run)
	return _c
}
