// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParameterFactory creates a new instance of MockParameterFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParameterFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParameterFactory {
	mock := &MockParameterFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParameterFactory is an autogenerated mock type for the ParameterFactory type
type MockParameterFactory struct {
	mock.Mock
}

type MockParameterFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParameterFactory) EXPECT() *MockParameterFactory_Expecter {
	return &MockParameterFactory_Expecter{mock: &_m.Mock}
}

// Parameters provides a mock function for the type MockParameterFactory
func (_mock *MockParameterFactory) Parameters() []entities.Parameter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parameters")
	}

	var r0 []entities.Parameter
	if returnFunc, ok := ret.Get(0).(func() []entities.Parameter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Parameter)
		}
	}
	return r0
}

// MockParameterFactory_Parameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parameters'
type MockParameterFactory_Parameters_Call struct {
	*mock.Call
}

// Parameters is a helper method to define mock.On call
func (_e *MockParameterFactory_Expecter) Parameters() *MockParameterFactory_Parameters_Call {
	return &MockParameterFactory_Parameters_Call{Call: _e.mock.On("Parameters")}
}

func (_c *MockParameterFactory_Parameters_Call) Run(run func()) *MockParameterFactory_Parameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterFactory_Parameters_Call) Return(parameters []entities.Parameter) *MockParameterFactory_Parameters_Call {
	_c.Call.Return(parameters)
	return _c
}

func (_c *MockParameterFactory_Parameters_Call) RunAndReturn(run func() []entities.Parameter) *MockParameterFactory_Parameters_Call {
	_c.Call.Return(run)
	return _c
}
