// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplicationDefinition creates a new instance of MockApplicationDefinition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationDefinition(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationDefinition {
	mock := &MockApplicationDefinition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplicationDefinition is an autogenerated mock type for the ApplicationDefinition type
type MockApplicationDefinition struct {
	mock.Mock
}

type MockApplicationDefinition_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationDefinition) EXPECT() *MockApplicationDefinition_Expecter {
	return &MockApplicationDefinition_Expecter{mock: &_m.Mock}
}

// Features provides a mock function for the type MockApplicationDefinition
func (_mock *MockApplicationDefinition) Features() definition.Features {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Features")
	}

	var r0 definition.Features
	if returnFunc, ok := ret.Get(0).(func() definition.Features); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(definition.Features)
	}
	return r0
}

// MockApplicationDefinition_Features_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Features'
type MockApplicationDefinition_Features_Call struct {
	*mock.Call
}

// Features is a helper method to define mock.On call
func (_e *MockApplicationDefinition_Expecter) Features() *MockApplicationDefinition_Features_Call {
	return &MockApplicationDefinition_Features_Call{Call: _e.mock.On("Features")}
}

func (_c *MockApplicationDefinition_Features_Call) Run(run func()) *MockApplicationDefinition_Features_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplicationDefinition_Features_Call) Return(features definition.Features) *MockApplicationDefinition_Features_Call {
	_c.Call.Return(features)
	return _c
}

func (_c *MockApplicationDefinition_Features_Call) RunAndReturn(run func() definition.Features) *MockApplicationDefinition_Features_Call {
	_c.Call.Return(run)
	return _c
}
